[project]
name = "gpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "regex>=2024.11.6",
]

[dependency-groups]
tests = [
    "hypothesis>=6.131.15",
    "pytest>=8.3.5",
    "transformers>=4.51.3",
]
